### ISSUE TITLE
feature request: new pictures more often

### ISSUE THREAD

**Issue by Inetov** [ORelio/Spotlight-Downloader#12]
Save a record that the picture was used (no matter for wallpapper or lockscreen) and select new ones based on the rating of frequency of use. It may also make sense to save the datetime of use.
Thus, we will see new pictures more often, and old ones will be displayed only if there are no new ones in the cache.

Now I have 50 images in the directory, many of which I have never seen, but when I run the script I getting the same ones over and over again.

I think it's may be very useful feature.

**Comment by ORelio** [comment]
As you noticed, 50 images is indeed not very convenient because it significantly reduces the set of images used for randomly picking one image. As a result, you're more likely to get the same images. 

For this reason, the existing scripts are written with two different approaches:

 - `update-lockscreen.bat` has a similar approach as stock Windows Spotlight: To minimize disk space, a few images are downloaded from the Spotlight API, which offers many images and is less likely to return the same ones over and over. On next refresh, all images in cache are wiped so fresh images are downloaded, randomly selected by the API. Refresh is not done on metered networks.

 - `update-archive-and-lockscreen.bat` uses a large cache initially built using spotlight-download-archive.bat. With hundreds of images in your cache, you're unlikely to get the same images over and over. The cache grows when new images are found, but takes less that 1 GB. This approach will minimize bandwidth and relies much less on the API. If it goes down some day, you have a copy of all the images you have ever seen, and plenty of new images you've never seen yet.

I'm using both scripts on various machines and the randomess is as good as stock Spotlight 😉

**Comment by Inetov** [comment]
What difference between 50 images and 1 GB archive?)
Without the frequency of use rating - we will getting the same ones again.

> the randomess is as good as stock Spotlight 😉

yes but stock Spotlight has like/dislike buttons and make it a lot harder)


ok, actually, I understand that my request also requires great improvements, but I propose to leave it open - at least as an idea)

**Comment by ORelio** [comment]
Sure, leaving this open.

**Comment by ORelio** [comment]
Interesting! So according to the link you posted, the PID should be `338387`?

> ## List of Subscription IDs
> 
> The same link also downloads Store Apps recommendations, Start Menu Tiles icon etc.
> From `CreativeFramework::TargetedContent::GetAdUnitIdFromSubscriptionId` arrays:
> 
> |        Subscription ID         |  Internal Ad ID  |  Public Ad ID  |
> |:------------------------------:|:----------------:|:--------------:|
> |  LockScreen*                   |  338380           |  338387*      |
>

**Comment by bytes0101** [comment]
I looked more into it. Yes, seems like the PID is not a pre-defined UUID of a Windows PC, but a general public ID to retrieve wallpapers which are specifically picked for Lockscreens by Microsoft. So 338387 should be the right one. It's also utilized [here](https://github.com/xyx0826/WinSpotlightDownloader/blob/master/WinSpotlightDownloader/MsnArcApi.cs).

I still don't know about the "lo" parameter yet.

**Comment by bytes0101** [comment]
#18 
I've removed the rafb and lo parameters as it's unclear what they do and the API request works fine without them

**Comment by ORelio** [comment]
Merged, thanks 👍

**Comment by yrtnsky** [comment]
Windows 11 got a feature to use Spotlight for wallpapers. It seems for background they are using different pool of images than for lock screen. Does anyone know how a request for these new images may look like?

**Comment by ORelio** [comment]
@yrtnsky Don't know yet. I'd recommend creating a new issue so that other people see it better.
