### ISSUE TITLE
Metadata title embed in picture

### ISSUE THREAD

**Issue by luigibrosse** [ORelio/Spotlight-Downloader#5]
Thanks a lot for the software. One thing I am missing is to have the title of the picture displayed in the picture (Spotlight for me was indicating what I was looking at, where it was taken, etc. on the top right). Do you believe you could implement this since you are already collecting the metadata during your API call?

**Comment by ORelio** [comment]
As far as I know, when defining static images, the widget is automatically hidden, and it is not possible to customize the layout of the lockscreen. However, it may be possible to insert a description directly into the picture when defining it as lockscreen image. I'll look into this.

**Comment by ORelio** [comment]
Now implemented as per [v1.4](https://github.com/ORelio/Spotlight-Downloader/releases/tag/v1.4). It should handle cropping/scaling depending on screen res and generate an embed with appropriate font size depending on the current screen scaling factor so that it looks natural on most systems. Tested on Windows 7 and Windows 10.

**Comment by luigibrosse** [comment]
Thanks. Will test tomorrow.

**Comment by luigibrosse** [comment]
Tested on Windows 10. Works like a charm. Can be closed. Thanks a lot.
