### ISSUE TITLE
Archive contains very few images

### ISSUE THREAD

**Issue by luigibrosse** [ORelio/Spotlight-Downloader#6]
I was wondering if there is a hard limit from your software on how many pictures are saved in the archive. Currently I have 75 pictures. Is that what is available on Microsoft server, or is it what you can download? Do you know if Microsoft sometimes refresh pictures, so my archive will eventually grow?

**Comment by ORelio** [comment]
Well, there is a limit, but not on the amount of images you can download. The API currently returns one random image. You cannot specifically request for a different image so as you request random images, it becomes more and more likely that images returned by the API are already in the archive. SpotlightDL does not know when to stop, so there is a hard limit of 50 consecutive unsuccessful API calls (images already archived) that will cause the download operation to stop. However, you can launch download again at a later time to discover more images as I suppose that they are periodically renewed. Since I created this app, my Archive folder progressively grew to around 1000 images at the moment.

**Comment by luigibrosse** [comment]
Thanks a lot for your explanation. I dug into your code and I realized that there was this 50 hard limit. However, having launched maybe 50 times the script in the last few days, I have managed to get only one extra image. This seems very low to me, especially considering the amount of pictures you mentioned or for that matter if you go to https://spotlight.it-notes.ru, the website has roughly 1200 pictures as well. So this means that the Spotlight service has probably a lot in stock.
Even if we admit that they are rotating them periodically and / or not having all of them available, I still believe that I should get more in my archive. I tried also to connect to the endpoint directly (via webbrowser) and I am able to get many more pictures that way (that are not in my archive). For me, this is a mystery.

**Comment by ORelio** [comment]
Implemented `--locale` as per release [1.4.1](https://github.com/ORelio/Spotlight-Downloader/releases/tag/v1.4.1).

**Comment by luigibrosse** [comment]
Will test and let you know.

**Comment by luigibrosse** [comment]
Thanks. Looks good on my end. Can be closed.

PS: great job with your documentation / FAQ.
