### ISSUE TITLE
locale collections

### ISSUE THREAD

**Issue by wstlxx** [ORelio/Spotlight-Downloader#7]
Greetings, I have successfully downloaded several images with Spotlight-Downloader

How am i able to know which country provide different images from mine?
Is there a list of available locales?
Is there a way to achieve as much images as possible from all locales in the world?
Thanks for your work!

**Comment by ORelio** [comment]
Hi,

By default, SpotlightDL will use the locale set on your computer, so it should get similar random images as your computer. You can override this using the `--locale` command-line parameter.

However, it is not possible to easily download all images from all over the world, because the API only gives random images, and I assume that images are periodically renewed. The best you can do is downloading as much images as possible using the provided download script, and relaunch it for different locales and/or at different times. Of course, metadata for each locale will include title in the associated language so you'll get mixed metadata.

I am not aware of a list of all locales supported by Microsoft Spotlight.

**Comment by Louvas** [comment]
Hello @ORelio ,

I've tested an extensive list of locales and added them to the command lines inside the .bat file so every time it finishes to execute one locale it goes to the next one and so on. As for today I was able to download +680 different images using 318 different locales.

I've attached the list of locales I've being using (most likely all that Spotlight supports - give or take). Hopefully this information will help to implement them within the code, making it possible to download as much images as possible without the hassle to edit the batch file to add hundreds of extra command lines.

Thank you!


[locales.txt](https://github.com/ORelio/Spotlight-Downloader/files/4548997/locales.txt)
